# Generated by Django 2.2 on 2019-05-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0003_auto_20190509_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='snippets', to='djangobin.Tag'),
        ),
    ]
