# Generated by Django 2.2 on 2019-05-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0004_auto_20190509_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
