# Generated by Django 2.2 on 2019-05-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0005_auto_20190509_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Language Code'),
        ),
    ]
