# Generated by Django 2.2 on 2019-05-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0006_auto_20190509_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='highlighted_code',
            field=models.TextField(blank=True, help_text='Read only field. Will contain the syntax-highlighted version of the original code.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='hits',
            field=models.IntegerField(default=0, help_text='Read only field. Will be updated after every visit to snippet.'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(help_text='Read only field. Will be filled automatically.'),
        ),
    ]
