# Generated by Django 2.2 on 2019-05-11 17:58

from django.db import migrations

LANGUAGES = [
    {
        'name': 'Bash',
        'lang_code': 'bash',
        'slug': 'bash',
        'mime': 'application/x-sh',
        'file_extension': '.sh',
    },
    {
        'name': 'C',
        'lang_code': 'c',
        'slug': 'c',
        'mime': 'text/x-chdr',
        'file_extension': '.c',

    },
    {
        'name': 'C#',
        'lang_code': 'c#',
        'slug': 'c-sharp',
        'mime': 'text/plain',
        'file_extension': '.aspx',
    },
    {
        'name': 'C++',
        'lang_code': 'c++',
        'slug': 'cpp',
        'mime': 'text/x-c++hdr',
        'file_extension': '.cpp',

    },
    {
        'name': 'Python',
        'lang_code': 'python',
        'slug': 'python',
        'mime': 'text/plain',
        'file_extension': '.py',
    },
    {
        'name': 'PHP',
        'lang_code': 'php',
        'slug': 'php',
        'mime': 'text/plain',
        'file_extension': '.php',
    },
]

# forward function
def add_languages(apps, schema_editor):
    Language = apps.get_model('djangobin', 'Language')

    for lang in LANGUAGES:
        l = Language.objects.get_or_create(
            name = lang['name'],
            lang_code = lang['lang_code'],
            slug = lang['slug'],
            mime = lang['mime'],
            file_extension = lang['file_extension'],
        )
        print(l)


def remove_languages(apps, schema_editor):
    Language = apps.get_model('djangobin', 'Language')

    for lang in LANGUAGES:
        l = Language.objects.get(
            lang_code=lang['lang_code'],
        )

        l.delete()


class Migration(migrations.Migration):


    dependencies = [
        ('djangobin', '0009_auto_20190511_1614'),
    ]

    operations = [
        migrations.RunPython(
            add_languages,
            remove_languages
        )
    ]
